# #############################
# Forecasting service infreastructure definition
# ######
version: "3.8"

networks:
  backnet:
    name: backnet

services:
  
  # #######################
  # Forecasting service
  # #######################
  forecasting-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sergiunagy/dev-finapp-forecaster
    container_name: dev-finapp-forecaster
    ports:
    - 5000:5000
    # mount volumes if you want hot reloads
    volumes:
      - "../src:/home/app"
    networks:
      backnet:
        aliases:
          - forecaster
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
